In [1]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")


In [2]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset
dataset.columns
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent=dataset[['charges']]
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)



In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [7]:
independent

age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [8]:
dependent=dataset[['charges']]

In [9]:
dependent

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)


In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train_scaled=sc.fit_transform(X_train)
X_test_scaled=sc.transform(X_test)

In [12]:
X_train

age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]

In [13]:
scy=StandardScaler()
Y_train_scaled=scy.fit_transform(Y_train)
Y_test_scaled=scy.transform(Y_test)

In [14]:
from sklearn.svm import SVR
regressor=SVR(kernel="rbf",C=1000)
regressor.fit(X_train_scaled,Y_train)

C:\Users\Windows\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1000, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [15]:
regressor.intercept_

array([14948.96194087])

In [16]:
regressor.n_support_

array([         0, 1072693248])

In [17]:
Y_pred_scaled=regressor.predict(X_test_scaled)
Y_pred_scaled=Y_pred_scaled.reshape(-1,1)

In [18]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,Y_pred_scaled)

In [19]:
r_score

0.8102064851758545

loaded_model=pickel.load(open("finalized_model_svr.sav", 'rb'))
result=loaded_model.predict(preinput)

In [20]:
import pickle
filename="finalized_model_svrdeployementpreinputout.sav"

In [21]:
pickle.dump(regressor,open(filename,'wb'))


In [26]:
preinput=sc.transform([[33,22.705,0,1,1]])

In [27]:
preinput

array([[-0.46205754, -1.29124462, -0.89833872,  1.02378711,  1.98149332]])

In [28]:
loaded_model=pickle.load(open("finalized_model_svrdeployementpreinputout.sav",'rb'))
result=loaded_model.predict(preinput)
result

array([17032.63107139])

In [29]:
preoutput=scy.inverse_transform([result])

In [30]:
preoutput

array([[2.02254647e+08]])